src/Entity/Structure.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use App\Repository\StructureRepository;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Validator\Constraints\Cascade;

#[ORM\Entity(repositoryClass: StructureRepository::class)]
#[ORM\Table(name: '`structures`')]
#[UniqueEntity(fields:'nameStructure', message:'Le nom que vous avez indiqué existe déjà')]
#[UniqueEntity(fields:'phone', message:'Le numéro de téléphone que vous avez indiqué existe déjà ')]

class Structure
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 50, unique:true)]
    private ?string $nameStructure = null;

    #[ORM\Column(length: 100)]
    private ?string $address = null;

    #[ORM\Column]
    private ?int $zipcode = null;

    #[ORM\Column(length: 50)]
    private ?string $city = null;

    #[ORM\Column(length: 50,unique:true)]
    private ?string $phone = null;

    #[ORM\Column]
    private ?bool $is_active = null;

    #[ORM\Column(length: 150, nullable: true)]
    private ?string $full_description = null;

    #[ORM\Column(length: 150, nullable: true)]
    private ?string $short_description = null;

    #[ORM\ManyToOne(inversedBy: 'structures')]
    private ?Partner $partner = null;

    #[ORM\ManyToOne(inversedBy: 'structure', cascade: ['persist', 'remove'])]
    private ?User $user = null;

    #[ORM\ManyToMany(targetEntity: Permission::class, inversedBy: 'structures')]
    private Collection $permissions;

    // #[ORM\OneToMany(mappedBy: 'structure', targetEntity: Permission::class)]
    // private Collection $permissions;

    public function __construct()
    {
        $this->permissions = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNameStructure(): ?string
    {
        return $this->nameStructure;
    }

    public function setNameStructure(string $nameStructure): self
    {
        $this->nameStructure = $nameStructure;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(string $address): self
    {
        $this->address = $address;

        return $this;
    }

    public function getZipcode(): ?int
    {
        return $this->zipcode;
    }

    public function setZipcode(int $zipcode): self
    {
        $this->zipcode = $zipcode;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getPhone(): ?string
    {
        return $this->phone;
    }

    public function setPhone(string $phone): self
    {
        $this->phone = $phone;

        return $this;
    }

    public function isIsActive(): ?bool
    {
        return $this->is_active;
    }

    public function setIsActive(bool $is_active): self
    {
        $this->is_active = $is_active;

        return $this;
    }

    public function getFullDescription(): ?string
    {
        return $this->full_description;
    }

    public function setFullDescription(?string $full_description): self
    {
        $this->full_description = $full_description;

        return $this;
    }

    public function getShortDescription(): ?string
    {
        return $this->short_description;
    }

    public function setShortDescription(?string $short_description): self
    {
        $this->short_description = $short_description;

        return $this;
    }


    public function getPartner(): ?Partner
    {
        return $this->partner;
    }

    public function setPartner(?Partner $partner): self
    {
        $this->partner = $partner;

        return $this;
    }

    

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }


    /**
     * @return Collection<int, Permission>
     */
    public function getPermissions(): Collection
    {
        return $this->permissions;
    }

    public function addPermission(Permission $permission): self
    {
        if (!$this->permissions->contains($permission)) {
            $this->permissions->add($permission);
        }

        return $this;
    }

    public function removePermission(Permission $permission): self
    {
        $this->permissions->removeElement($permission);

        return $this;
    }
}

src/Form/StructureType.php
<?php

namespace App\Form;

use App\Entity\User;
use App\Entity\Partner;
use App\Entity\Structure;
use App\Entity\Permission;
use App\Repository\UserRepository;
use Doctrine\ORM\EntityRepository;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Validator\Constraints\Length;
use Symfony\Component\Validator\Constraints\NotBlank;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;

class StructureType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            //RECUP LA COLLECTION DE PARTNER
            ->add('partner', EntityType::class,[
                'class'=> Partner::class,
                'required'=> true,
                'label'=> 'Selectionner une franchise',
                'placeholder'=>'Choisissez...',
                'choice_label'=> function (Partner $partner){
                    return $partner->getNamePartner();
                },
                // Classer par ordre alphabétiq
                'query_builder' => function (EntityRepository $er) {
                    return $er->createQueryBuilder('p')
                        ->orderBy('p.namePartner', 'ASC');
                },
    
                
            ])

            //RECUP LA COLLECTION DE USER
            ->add('user', EntityType::class,[
                'label'=> 'Selectionner un compte de connexion',
                'class'=> User::class,
                'required'=> true,
                'placeholder'=>'Choisissez...',
                'choice_label'=> function (User $user){
                    return $user->getUsername();
                },
                // Recup uniquement ROLE_STRUCTURE
                'query_builder' => function (UserRepository $userRepo) {
                    $qb = $userRepo->createQueryBuilder('u');
                    return $qb
                        ->where('u.roles LIKE :role')
                        ->setParameter('role', '%"' . 'ROLE_STRUCTURE' . '"%')
                        ->orderBy('u.username');}

            ])

            ->add('nameStructure', TextType::class,[
                'label'=> 'Nom de la structure',
                'attr'=>[
                'placeholder'=>'Nom du gérant de la structure',
                ],
                'required'=> true,
                'constraints'=> [
                    new NotBlank(['message'=> 'Le champ ne peut pas être vide !']),
                    new Length([
                        'min'=> 2, 'max'=> 100, 'minMessage' =>'Le nom doit faire entre {{ limit }} et {{ limit }} caractères', 'maxMessage' =>'Le nom doit faire entre {{ limit }} et {{ limit }} caractères']),
                    ]       
                ])  
                
            ->add('address', TextType::class,[
                'label'=> 'Adresse de la structure ',
                'attr'=>[
                'placeholder'=>'3 avenue de la mer',
                ],
                'required'=> true, 
                'constraints'=> [
                    new NotBlank(['message'=> 'Le champ ne peut pas être vide !']),
                    new Length([
                        'min'=> 2, 'max'=> 255, 'minMessage' =>'L\'adresse doit faire entre {{ limit }} et {{ limit }} caractères', 'maxMessage' =>'L\'adresse doit faire entre {{ limit }} et {{ limit }} caractères']),
                    ]       
            ])
            ->add('zipcode', TextType::class,[
                'label'=> 'Code Postal',
                'attr'=>[
                'placeholder'=>'exemple 34000',
                ],
                'required'=> true, 
                'constraints'=> [
                    new NotBlank(['message'=> 'Veuillez saisir un code postal valide !']),
                    new Length([
                        'min'=> 5, 'max'=> 5, 'minMessage' =>'Le code postal doit faire entre {{ limit }} et {{ limit }} caractères', 'maxMessage' =>'Le code postal doit faire entre {{ limit }} et {{ limit }} caractères']),
                ]
            ])
            ->add('city', TextType::class,[
                'label'=> 'Ville',
                'attr'=>[
                'placeholder'=>'Montpellier',
                ],
                'required'=> true, 
                'constraints'=> [
                    new NotBlank(['message'=> 'Veuillez saisir une ville valide !']),
                    new Length([
                        'min'=> 2, 'max'=> 100, 'minMessage' =>'Le champ doit faire entre {{ limit }} et {{ limit }} caractères', 'maxMessage' =>'Le champ doit faire entre {{ limit }} et {{ limit }} caractères']),
                ]
            ])
            ->add('phone', TextType::class,[
                'label'=> 'Téléphone de la structure',
                'attr'=>[
                'placeholder'=>'exemple 0617236985',
                ],
                'required'=> true, 
                'constraints'=> [
                    new NotBlank(['message'=> 'Veuillez saisir un numéro de téléphone valide !']),
                ]
            ])
            

            ->add('is_active', CheckboxType::class,[
                'label'=> 'Activer la structure',
                'required'=> false 
                ])
                
            
            ->add('short_description', TextareaType::class,[
                'label'=> 'Courte description ',
                'required'=> false,
                'attr'=>[
                'placeholder'=>'Détail de la structure ...',
                ],    
            ])

            //RECUP LA COLLECTION DE Permissions
            ->add('permissions', EntityType::class, [
                'class' => Permission::class,
                'required' => true,
                'label' => 'Choisissez les options',
                'choice_label'=> 'titre',
                'multiple' => true,
                'placeholder' => 'Choisissez la Franchise',
                'expanded' => true,
                'choice_label' => function (Permission $permission) {
                    return $permission->getTitle();
                    },
                    'query_builder' => function (EntityRepository $er) {
        return $er->createQueryBuilder('p')
            ->orderBy('p.title', 'ASC');
                },
                // Classer par ordre alphabétiq
                // 'query_builder' => function (EntityRepository $er) {
                //     return $er->createQueryBuilder('p')
                //         ->orderBy('p.namePartner', 'ASC');
                // },


            ])
            // ->add('short_description', TextType::class,[
            //     'label'=> 'Courte Description',
            //     'required'=> false,
            //     'attr'=>[
            //     'placeholder'=>'...',
            //     ],
            // ])
            
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        //vers quel objet le form va être lié
        $resolver->setDefaults([
            'data_class' => Structure::class,
            'csrf_protection' => true,
            'csrf_field_name' => '_token',
            'csrf_token_id' => 'structure_item',
        ]);
    }
}

src/Controller/StructureController.php
<?php

namespace App\Controller;

use App\Entity\User;
use App\Form\UserType;
use App\Entity\Partner;
use App\Entity\Structure;
use App\Service\MailService;
use App\Repository\StructureRepository;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface;



/**
 * Route pour les structures uniquement avec détail de leurs structures
 */

#[Route('/structure')]
class StructureController extends AbstractController
{
    #[Route('/show/{id<\d+>}', name: 'app_structure_show')]

    public function index(ManagerRegistry $doctrine, int $id): Response
    {

        // $repositoryUser = $doctrine->getRepository(User::class);
        // $userId = $repositoryUser->find($id);
        // $repositoryPartner = $doctrine->getRepository(Partner::class);
        // $partner = $repositoryPartner->find($id);

        $repositoryStructure = $doctrine->getRepository(Structure::class);
        $structure = $repositoryStructure->find($id);
        $permissions = $structure->getPermissions();

        // $structure = $user->getStructure();
        
        return $this->render('structure/index.html.twig',[
            'structure'=> $structure,
            'permissions' => $permissions,

        ]);
    }
    /**
     * Change Email + MDP 
     */
    #[Route('/edit/{id<\d+>}/', name: 'app_structure_edit')]
    public function editUser(Request $request, UserPasswordHasherInterface $userPasswordHasher, EntityManagerInterface $entityManager, User $user = null, MailService $mail, StructureRepository $structureRepo): Response
    {
        /**
         * @var User $user 
         */
        $user = $this->getUser();
        if (!$user) {
            $user = new User();
        }
        $form = $this->createForm(UserType::class, $user);
        
        $form->handleRequest($request);

        //S'assure de la validité du form et que les valaurs sont cohérentes
        if ($form->isSubmitted() && $form->isValid()) {
            if (!$user->getId()) {
            }
            $user->setPassword(
                $userPasswordHasher->hashPassword(
                    $user,

                    // pour modifier son mot de passe
                    //récup les données saisies par l'utilisateur.
                    $form->get('password')->getData()
                )
            );
            // Ajoute des partners aux user
            $partners = $user->getPartner();
            foreach ($partners as $partner) {
                $user->addPartner($partner);
            }

            // Ajoute des structures aux user
            $structures = $user->getStructure();
            foreach ($structures as $structure) {
                $user->addStructure($structure);
            }

            $entityManager->persist($user);
            $entityManager->flush();

            $this->addFlash('success', 'Le compte de connexion a bien été modifié');

            $mail->sendEmail(
                'fitnessDrive@outlook.fr',
                $user->getEmail(),
                'Modification de votre compte',
                'editUser',
                compact('user')

            );
            $this->addFlash('send', 'Email de modification a bien été envoyé');
        }
        $structure = $structureRepo->findOneByName($user->getUsername());

        return $this->render('structure/user/editUser.html.twig', [
            'formUser' => $form->createView(),

            //Variable in editMode
            'editMode' => $user->getId() !== null,
            'h1Edit' => $user->getUsername() !== null,
            'structures'=>$structure,
        ]);
    }

}

templates/structure/_show.html.twig
<div class="d-flex justify-content-center ">
    <div class="card" >
        <div class="card-body">
            <h5 class="card-title text-center">Fitness Drive
                <br>
                {{structure.namestructure}}
            </h5>

            <div class="d-block d-sm-flex justify-content-sm-between">
                <p class="text-muted">Gérant :
                    {{structure.user.username}}
                </p>
                <!-- Structure Active ? -->
                <p>{{ structure.isActive ? 
                '<span class="p-2">Active</span><svg xmlns="http://www.w3.org/2000/svg" width="12" height="12" fill="currentColor" class="bi bi-circle-fill text-primary" viewbox="0 0 16 16"><circle cx="8" cy="8" r="8"/></svg>' :'<span class="p-2">InActive</span><svg xmlns="http://www.w3.org/2000/svg" width="12" height="12" fill="currentColor" class="bi bi-circle-fill text-danger" viewbox="0 0 16 16"><circle cx="8" cy="8" r="8"/></svg>'}}
                </p>
            </div>

            <p class="card-text">
                <ul>
                    <li>
                        <a class='info' href="mailto:{{structure.user.email}} ">
                            <i class="fa fa-envelope p-2" aria-hidden="true"></i>
                            {{structure.user.email}}</a>
                    </li>
                    <li>
                        <a class='info' href="tel:{{structure.phone}} ">
                            <i class="fa fa-phone p-2" aria-hidden="true"></i>
                            {{structure.phone}}</a>
                    </li>
                </ul>        
            </p>
        </div>
    </div>
</div>

<section>

	<h4 class="titleStructure  mt-4">
		<u>Vos permissions</u>
		:</h4>

	{% for permission in permissions %}
		<div class="perms">
			<h5>
				<strong>{{permission.title}}</strong>
			</h5>
			<p>
				{% if structure.isActive %}
					<span class="">Active</span>
					<svg xmlns="http://www.w3.org/2000/svg" width="12" height="12" fill="currentColor" class="bi bi-circle-fill text-primary " viewbox="0 0 16 16"><circle cx="8" cy="8" r="8"/></svg>
				{% else %}
					<span class="">InActive</span>
					<svg xmlns="http://www.w3.org/2000/svg" width="12" height="12" fill="currentColor" class="bi bi-circle-fill text-danger" viewbox="0 0 16 16"><circle cx="8" cy="8" r="8"/></svg>
				{% endif %}
			</p>
		</div>

	{% else %}
		<div class="alert alert-success text-center">
			<p>Vous n'avez aucune permission !</p>
		</div>
	{% endfor %}

</section>

        

templates/structure/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Struture | {{ parent() }}{% endblock %}

{% block body %}
<body class="bgStructure">

        {% block navbar %} 
			{% include "_partials/_navbarClient.html.twig" %}
        {% endblock %}

    <main class="container-fluid " id='backS'>

    {% if app.user %}
        <div class="d-flex justify-content-end align-item-center">
            <a class=' textGreen' alt="Vous êtes connecté en tant que {{ app.user.username }}" title="Vous êtes connecté en tant que {{ app.user.username }}"><i class="fas fa-user-circle  p-1"></i>{{ app.user.username }}</a>
        </div>
    {% endif %}

        <div class="row">
            <div class="col-12">
                <h2 class=" mb-4 mt-4 titleStructure">Fitness Drive <br>
                    {{structure.nameStructure}}</h2>
            </div>
        </div>

		{% include "structure/_show.html.twig" %}

		<a class="rocket textGreen back" href='#backS'>
			<i class="fa fa-rocket " alt="Retour en haut" title="Retour en haut"></i>
		</a>

    </main> 
</body>
{% endblock %}

templates/structure/structure.html.twig
{% extends 'base.html.twig' %}

{% block title %}Struture| {{ parent() }}{% endblock %}



{% block body %}
    <header>
        {% block navbar %} {{ parent()}} {% endblock %}
    </header>


    <main class="container">

    <h2>Bienvenue sur votre compte   "structure"</h2>

    <p>Voici vos permissions</p>

<h3>Le nom est : </h3>
        <p>{{ structure.user.username }}</p>

    <h3>Son email est : </h3>
        <p>{{ structure.user.email }}</p>

    <h3>Son password est :</h3>
        <p>{{ structure.user.password }}</p>
        <p>{{ structure.nameStructure }}</p>


        {{ dump(structure) }}

</main> 
{% endblock %}